import type { ImageAssetStorage } from '../images/image-asset-storage';
import {
  characterSheetKeyForNamespace,
  claimCharacterSheetAssetKey,
  claimImageAssetKey,
  imageKeyForNamespace,
} from '../images/image-asset-storage';
import {
  namespacesEqual,
  type ClaimArtifactNamespace,
  type GenerationArtifactNamespace,
} from './generation-artifact-namespace';

/**
 * Phase B, Slice B3 — the copy-forward-or-generate algorithm shared by every
 * claim-scoped character sheet and generated image. Implements the ordering
 * from the Phase B proposal:
 *
 *   1. A valid current-claim artifact always wins (idempotent re-entry).
 *   2. Otherwise, if a distinct source namespace was resolved, inspect the
 *      exact source key and copy it forward via ImageAssetStorage.
 *      copyImageAsset (server-side, never through this process's memory).
 *   3. Otherwise (no source, or the source is missing/invalid/disappears
 *      before the copy lands), the caller must generate a fresh artifact
 *      into the current-claim key.
 *
 * Operational storage errors (auth/network failures from getImageAsset or
 * copyImageAsset) are never caught here — they propagate to the caller
 * exactly like every other unexpected AgentService failure, so they can
 * never be silently reclassified as "missing source" (which would trigger a
 * silent regeneration) or as a successful reuse.
 */
export type ClaimArtifactSourceStatus = 'valid' | 'missing' | 'invalid' | 'not-checked';

export interface ClaimArtifactResolution {
  /** The current-claim key the caller must read bytes from (if reused/copied) or write freshly generated bytes to (if 'regenerate'). */
  readonly key: string;
  readonly outcome: 'reused' | 'copied' | 'regenerate';
  /** Status of the source key inspected before this resolution, for resume diagnostics — 'not-checked' when no source was ever consulted (current-claim was already valid, or no source namespace applies). */
  readonly sourceStatus: ClaimArtifactSourceStatus;
}

async function resolveArtifact(
  storage: ImageAssetStorage,
  currentKey: string,
  sourceKey: string | null,
): Promise<ClaimArtifactResolution> {
  const currentBuffer = await storage.getImageAsset(currentKey);
  if (currentBuffer != null && currentBuffer.length > 0) {
    return { key: currentKey, outcome: 'reused', sourceStatus: 'not-checked' };
  }
  if (!sourceKey) {
    return { key: currentKey, outcome: 'regenerate', sourceStatus: 'not-checked' };
  }

  const sourceBuffer = await storage.getImageAsset(sourceKey);
  if (sourceBuffer == null) {
    return { key: currentKey, outcome: 'regenerate', sourceStatus: 'missing' };
  }
  if (sourceBuffer.length === 0) {
    return { key: currentKey, outcome: 'regenerate', sourceStatus: 'invalid' };
  }

  // Propagates on any operational failure (permission/network/etc.) — only a
  // genuinely missing source resolves to undefined (see copyImageAsset's own
  // doc comment in image-asset-storage.ts).
  const copied = await storage.copyImageAsset(sourceKey, currentKey);
  if (!copied) {
    // The source existed a moment ago (checked above) but disappeared before
    // the copy landed — treated the same as an ordinary missing source.
    return { key: currentKey, outcome: 'regenerate', sourceStatus: 'missing' };
  }

  const verifyBuffer = await storage.getImageAsset(currentKey);
  if (verifyBuffer == null || verifyBuffer.length === 0) {
    return { key: currentKey, outcome: 'regenerate', sourceStatus: 'invalid' };
  }
  return { key: currentKey, outcome: 'copied', sourceStatus: 'valid' };
}

/**
 * Resolves one planned cover/page/back_cover image against the current claim
 * namespace, copying it forward from `sourceNamespace` when needed.
 * `sourceNamespace` must be `null` whenever copy-forward must not be
 * attempted at all (e.g. the run's input changed since the source JSON was
 * produced — see AgentService's `resumable` gate) — passing the resolved
 * Book pointer unconditionally would let a regenerate-after-edit silently
 * reuse illustrations planned for the *old* story.
 */
export async function resolveImageArtifact(params: {
  storage: ImageAssetStorage;
  bookId: string;
  currentNamespace: ClaimArtifactNamespace;
  sourceNamespace: GenerationArtifactNamespace | null;
  kind: 'cover' | 'page' | 'back_cover';
  pageNumber?: number | undefined;
}): Promise<ClaimArtifactResolution> {
  const { storage, bookId, currentNamespace, sourceNamespace, kind, pageNumber } = params;
  const currentKey = claimImageAssetKey(bookId, currentNamespace, kind, pageNumber);
  const sourceKey =
    sourceNamespace && !namespacesEqual(currentNamespace, sourceNamespace)
      ? imageKeyForNamespace(bookId, sourceNamespace, kind, pageNumber)
      : null;
  return resolveArtifact(storage, currentKey, sourceKey);
}

/** Character-sheet counterpart to resolveImageArtifact — see its doc comment. */
export async function resolveCharacterSheetArtifact(params: {
  storage: ImageAssetStorage;
  bookId: string;
  currentNamespace: ClaimArtifactNamespace;
  sourceNamespace: GenerationArtifactNamespace | null;
}): Promise<ClaimArtifactResolution> {
  const { storage, bookId, currentNamespace, sourceNamespace } = params;
  const currentKey = claimCharacterSheetAssetKey(bookId, currentNamespace);
  const sourceKey =
    sourceNamespace && !namespacesEqual(currentNamespace, sourceNamespace)
      ? characterSheetKeyForNamespace(bookId, sourceNamespace)
      : null;
  return resolveArtifact(storage, currentKey, sourceKey);
}
