import { MIN_BOOK_PAGE_COUNT, type GenerationDiagnosticsDto } from '@book/types';

/**
 * Extra safe/non-secret fields the smoke script computes itself (from the
 * Book row, its AgentLog rows, and PdfStorage) that aren't part of the
 * shared GenerationDiagnosticsDto — kept local to this script rather than
 * widening the production diagnostics DTO/endpoint/frontend for a QA-only
 * concern. Same safety bar as GenerationDiagnosticsDto: identifiers only,
 * never bytes/paths/secrets.
 */
export interface SmokeValidationExtras {
  /** Total illustrations planned for this book (cover + pages + back cover), regardless of how many were actually attempted. */
  expectedImageCount: number;
  /** Planned illustrations left without real generated bytes this run — always 0 for a `complete` book, since pdf_render requires every one resolved. */
  fallbackImageCount: number;
  /** Stable, non-secret storage key for the character-sheet asset (not a filesystem path) — see characterSheetAssetKey() in image-asset-storage.ts. */
  characterSheetAssetId?: string;
  /** Provider that produced (or fell back to produce) the CharacterProfile — from the char_build AgentLog row. */
  characterProfileProvider: string;
  /** Whether PdfStorage confirms readable PDF bytes exist for this book right now. */
  pdfExists: boolean;
  /** Rendered PDF size in bytes (never the bytes themselves), when readable. */
  pdfSizeBytes?: number;
}

/**
 * Formats a GenerationDiagnosticsDto (already safe/non-secret — see
 * generation-diagnostics.ts) plus this script's own SmokeValidationExtras
 * into the smoke script's console summary. Pure function so it's
 * unit-testable without booting Nest or hitting the network. Only ever
 * prints fields already proven safe by GenerationDiagnosticsDto/
 * GenerationMetadata/SmokeValidationExtras — never an API key, a raw prompt,
 * or image bytes/base64.
 */
export function formatDiagnosticsSummary(
  diagnostics: GenerationDiagnosticsDto,
  extras?: SmokeValidationExtras,
): string {
  const meta = diagnostics.generationMetadata;
  const lines = [
    `  Book id:            ${diagnostics.bookId}`,
    `  Status:             ${diagnostics.status}`,
    `  Story provider:     ${meta.storyProvider}${meta.storyModel ? ` (${meta.storyModel})` : ''}`,
    `  Image provider:     ${meta.imageProvider}${meta.imageModel ? ` (${meta.imageModel})` : ''}`,
    `  Char. profile prov.:${extras ? ` ${extras.characterProfileProvider}` : ' n/a'}`,
    `  Generated pages:    ${meta.generatedPages ?? 'n/a'}`,
    `  Expected images:    ${extras?.expectedImageCount ?? 'n/a'}`,
    `  Generated images:   ${meta.generatedImageCount ?? 'n/a'}`,
    `  Fallback images:    ${extras?.fallbackImageCount ?? meta.failedImageCount ?? 'n/a'}`,
    `  Duration:           ${meta.durationMs !== undefined ? `${meta.durationMs}ms` : 'n/a'}`,
    `  PDF preview url:    ${diagnostics.previewPdfUrl ?? 'n/a'}`,
    `  PDF exists:         ${extras ? (extras.pdfExists ? 'yes' : 'no') : 'n/a'}`,
    `  PDF size > 0:       ${extras?.pdfSizeBytes !== undefined ? `${extras.pdfSizeBytes > 0 ? 'yes' : 'no'} (${extras.pdfSizeBytes} bytes)` : 'n/a'}`,
    `  Character sheet:    ${diagnostics.characterPersonalization.characterSheetGenerated ? 'generated' : 'not generated'}`,
    `  Char. sheet asset:  ${extras?.characterSheetAssetId ?? 'n/a'}`,
    `  Reference available:${diagnostics.characterPersonalization.characterReferenceAvailable ? ' yes' : ' no'}`,
    `  Reference used:     ${diagnostics.characterPersonalization.characterReferenceUsedForImages ? 'yes' : 'no'}`,
    `  Image gen mode:     ${diagnostics.characterPersonalization.imageGenerationMode}`,
    `  Diagnostics URL:    /api/books/${diagnostics.bookId}/generation-diagnostics`,
  ];
  if (diagnostics.failedStep) {
    lines.push(`  Failed step:        ${diagnostics.failedStep}`);
  }
  if (diagnostics.errorMessage) {
    lines.push(`  Error:              ${diagnostics.errorMessage}`);
  }
  return lines.join('\n');
}

/** Resolved, ready-to-use local QA book configuration — every field has a safe default. */
export interface SmokeBookConfig {
  childName: string;
  childAge: number;
  language: string;
  theme: string;
  pageCount: number;
  /** Optional local filesystem path to a jpg/png/webp reference photo of the child. */
  childPhotoPath?: string;
}

const DEFAULT_SMOKE_CHILD_NAME = 'Smoke';
const DEFAULT_SMOKE_CHILD_AGE = 5;
const DEFAULT_SMOKE_LANGUAGE = 'en';
const DEFAULT_SMOKE_THEME = 'friendship';
/**
 * Cheapest real-cost page count for a fully "complete" personalized book.
 * MIN_BOOK_PAGE_COUNT (4) is a hard floor — resolveTargetPageCount
 * (story-generation-provider.ts) clamps anything lower back up to it — and
 * every planned illustration must succeed for the book to reach `complete`
 * (see assertAllImagesResolved in pdf-rendering.md), so there's no cheaper
 * page count that still exercises the full real pipeline end to end.
 */
const DEFAULT_SMOKE_PAGE_COUNT = MIN_BOOK_PAGE_COUNT;

/**
 * Reads the optional SMOKE_CHILD_NAME / SMOKE_CHILD_AGE / SMOKE_LANGUAGE /
 * SMOKE_THEME / SMOKE_PAGE_COUNT / SMOKE_CHILD_PHOTO_PATH env vars, falling
 * back to safe defaults for any that are unset or malformed. Pure function —
 * no filesystem or network access — so it's unit-testable directly.
 */
export function resolveSmokeBookConfig(env: NodeJS.ProcessEnv): SmokeBookConfig {
  const childName = env['SMOKE_CHILD_NAME']?.trim() || DEFAULT_SMOKE_CHILD_NAME;
  const parsedAge = env['SMOKE_CHILD_AGE'] ? Number(env['SMOKE_CHILD_AGE']) : NaN;
  const childAge =
    Number.isFinite(parsedAge) && parsedAge > 0 ? Math.floor(parsedAge) : DEFAULT_SMOKE_CHILD_AGE;
  const language = env['SMOKE_LANGUAGE']?.trim() || DEFAULT_SMOKE_LANGUAGE;
  const theme = env['SMOKE_THEME']?.trim() || DEFAULT_SMOKE_THEME;
  const parsedPageCount = env['SMOKE_PAGE_COUNT'] ? Number(env['SMOKE_PAGE_COUNT']) : NaN;
  const pageCount =
    Number.isFinite(parsedPageCount) && parsedPageCount > 0
      ? Math.floor(parsedPageCount)
      : DEFAULT_SMOKE_PAGE_COUNT;
  const childPhotoPath = env['SMOKE_CHILD_PHOTO_PATH']?.trim() || undefined;

  return {
    childName,
    childAge,
    language,
    theme,
    pageCount,
    ...(childPhotoPath !== undefined && { childPhotoPath }),
  };
}

/** Returns a clear message (never null) when preconditions aren't met, so main() can fail fast before booting Nest. */
export function checkPreconditions(env: NodeJS.ProcessEnv): string | null {
  if (!env['OPENAI_API_KEY']) {
    return 'OPENAI_API_KEY is required to run the real generation smoke test.';
  }

  const storyProvider = env['STORY_GENERATION_PROVIDER']?.trim().toLowerCase();
  const imageProvider = env['IMAGE_GENERATION_PROVIDER']?.trim().toLowerCase();
  if (storyProvider !== 'openai' || imageProvider !== 'openai') {
    return [
      'STORY_GENERATION_PROVIDER and IMAGE_GENERATION_PROVIDER must both be "openai" to run this smoke test.',
      `  STORY_GENERATION_PROVIDER=${storyProvider ?? '(unset)'}`,
      `  IMAGE_GENERATION_PROVIDER=${imageProvider ?? '(unset)'}`,
      'Set both to "openai" and re-run. This script never runs against mock providers — that path is already covered by the normal test suite.',
    ].join('\n');
  }

  return null;
}
